import type { Metadata } from "next";
import { Junge } from "next/font/google";
import "./globals.css";

const junge = Junge({
  weight: '400', // Atau 'variable' jika ingin kontrol weight
  subsets: ["latin"],
  variable: "--font-junge",
  display: 'swap', // Untuk menghindari FOIT (Flash of Invisible Text)
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={junge.variable}>
      <body className="font-sans antialiased">
        {children}
      </body>
    </html>
  );
}